mount:
  /boot/efi:
    device:     # required, such as /dev/sda1
    format: false
  /:
    device:     # required, such as /dev/sda2, /dev/vda2, /dev/mapper/cryptroot
    label: ARCH
    subvolumes:
      cow:
        - boot
        - root
        - srv
        - var/log
        - var/crash
        - var/spool
        - var/lib/docker
        - var/lib/containers
      nocow:
        - var/tmp
        - var/cache
        - var/lib/libvirt/images
        - .swap     # If you need a Swapfile, create in this folder
  /home:
    device:     # not required
    label: HOME
    subvolumes:
      cow:
        - ${USER}/.var
        - ${USER}/.local/share/Steam
        - ${USER}/.local/share/docker
        - ${USER}/.local/share/containers
      nocow:
        - ${USER}/.cache
  /media/HOME:
    device: /home     # only works if /home is a device
    symlink:
      Desktop:        /home/${USER}/Desktop
      Documents:      /home/${USER}/Documents
      Downloads:      /home/${USER}/Downloads
      Music:          /home/${USER}/Music
      Pictures:       /home/${USER}/Pictures
      Public:         /home/${USER}/Public
      Videos:         /home/${USER}/Videos

      # Additional folders
      Nextcloud:      /home/${USER}/Nextcloud
      Projects:       /home/${USER}/Projects
      vmware:         /home/${USER}/vmware
      VirtualBox VMs: /home/${USER}/VirtualBox VMs
  swap:
    zram: auto
    # swapfile:
    #   path: /.swap/swapfile
    #   size: auto
config:
  locale: en_US
  kblayout:
  LC_ADDRESS:   # Convention used for formatting of street or postal addresses
  LC_ALL:       # Overrides all other locale variables (except LANGUAGE)
  LC_COLLATE:   # Collation order, affected by `ls`, for example.
  LC_CTYPE:     # Character classification and case conversion
  LC_MONETARY:  # Monetary formatting
  # LC_MEASUREMENT: th_TH.UTF-8 UTF-8   # Default measurement system used within the region
  LC_MESSAGES:  # Format of interactive words and responses
  LC_NUMERIC:   # Numeric formatting
  # LC_PAPER: th_TH.UTF-8 UTF-8    # Default paper size for region
  LC_RESPONSE:  # Determines how responses (such as Yes and No) appear in the local language
  LC_TELEPHONE: # Conventions used for representation of telephone numbers
  LC_TIME:      # Date and time formats
  # TZ: Asia/Bangkok    # Can also be autogenerated
bootloader:
  grub:
    - --modules="normal test efi_gop efi_uga search echo linux all_video gfxmenu gfxterm_background gfxterm_menu gfxterm loadenv configfile tpm gzio part_gpt btrfs"
    - --disable-shim-lock'
  refind: true    # It is possible to disable rEFInd
pkg:
  pacman:
    - linux
    - ${microcode}  # resolve to AMD or Intel -ucode
  aur:
    runner: paru
users:
  root:
    shell: /bin/zsh
  ${USER}:        # First wheel user will be used to install
    shell: /bin/zsh
    groups: wheel
